const GET_QUESTION_SET_REQUEST = "GET_QUESTION_SET_REQUEST";
const GET_QUESTION_SET_SUCCESS = "GET_QUESTION_SET_SUCCESS";
const GET_QUESTION_SET_FAILURE = "GET_QUESTION_SET_FAILURE";
const GET_ALL_CANDIDATE_ANS_REQUEST = "GET_ALL_CANDIDATE_ANS_REQUEST";
const GET_ALL_CANDIDATE_ANS_SUCCESS = "GET_ALL_CANDIDATE_ANS_SUCCESS";
const GET_ALL_CANDIDATE_ANS_FAILURE = "GET_ALL_CANDIDATE_ANS_FAILURE";
const POST_CANDIDATE_ANS_REQUEST = "POST_CANDIDATE_ANS_REQUEST";
const POST_CANDIDATE_ANS_SUCCESS = "POST_CANDIDATE_ANS_SUCCESS";
const POST_CANDIDATE_ANS_FAILURE = "POST_CANDIDATE_ANS_FAILURE";
const SET_IN_PROGRESS_TEST = "SET_IN_PROGRESS_TEST";
const REMOVE_IN_PROGRESS_TEST = "REMOVE_IN_PROGRESS_TEST";
const MARK_CANDIDATE_ANS_REQUEST = "MARK_CANDIDATE_ANS_REQUEST";
const MARK_CANDIDATE_ANS_SUCCESS = "MARK_CANDIDATE_ANS_SUCCESS";
const MARK_CANDIDATE_ANS_FAILURE = "MARK_CANDIDATE_ANS_FAILURE";
export const types = {
  GET_ALL_CANDIDATE_ANS_FAILURE,
  GET_ALL_CANDIDATE_ANS_REQUEST,
  GET_ALL_CANDIDATE_ANS_SUCCESS,
  GET_QUESTION_SET_FAILURE,
  GET_QUESTION_SET_REQUEST,
  GET_QUESTION_SET_SUCCESS,
  POST_CANDIDATE_ANS_REQUEST,
  POST_CANDIDATE_ANS_SUCCESS,
  POST_CANDIDATE_ANS_FAILURE,
  REMOVE_IN_PROGRESS_TEST,
  SET_IN_PROGRESS_TEST,
  MARK_CANDIDATE_ANS_REQUEST,
  MARK_CANDIDATE_ANS_SUCCESS,
  MARK_CANDIDATE_ANS_FAILURE,
};
