const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
const GET_VIDEOS_FAILURE = "GET_VIDEOS_FAILURE";
const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
export const types = {
  GET_CATEGORIES_FAILURE,
  GET_CATEGORIES_REQUEST,
  GET_CATEGORIES_SUCCESS,
  GET_VIDEOS_FAILURE,
  GET_VIDEOS_REQUEST,
  GET_VIDEOS_SUCCESS,
};
