export const hobbies_list = [
  '3D printing',
  'Acting',
  'Amateur radio',
  'Animation',
  'Aquascaping',
  'Astrology',
  'Art',
  'Baton twirling',
  'Binge-watching',
  'Blogging',
  'Board/tabletop games',
  'Book discussion clubs',
  'Book restoration',
  'Bowling',
  'Brazilian jiu-jitsu',
  'Breadmaking',
  'Building',
  'Bullet journaling',
  'Cabaret',
  'Calligraphy',
  'Candle making',
  'Candy making',
  'Car fixing & building',
  'Card games',
  'Cardistry',
  'Camgirl',
  'Ceramics',
  'Cheesemaking',
  'Chess',
  'Cleaning',
  'Clothesmaking',
  'Coffee roasting',
  'Collecting',
  'Coloring',
  'Communication',
  'Computer programming',
  'Confectionery',
  'Construction',
  'Cooking',
  'Cosplaying',
  'Couponing',
  'Craft',
  'Creative writing',
  'Crocheting',
  'Cross-stitch',
  'Crossword puzzles',
  'Cryptography',
  'Cue sports',
  'Dance',
  'Dancing',
  'Digital arts',
  'Distro Hopping',
  'DJing',
  'Diving',
  'Do it yourself',
  'Drama',
  'Drawing',
  'Drink mixing',
  'Drinking',
  'Electronic games',
  'Electronics',
  'Embroidery',
  'Experimenting',
  'Fantasy sports',
  'Fashion',
  'Fashion design',
  'Fishfarming',
  'Fishkeeping',
  'Filmmaking',
  'Flower arranging',
  'Fly tying',
  'Foreign language learning',
  'Furniture building',
  'Gaming (tabletop games and role-playing games)',
  'Genealogy',
  'Gingerbread house making',
  'Glassblowing',
  'Graphic design',
  'Gunsmithing',
  'Gymnastics',
  'Hacking',
  'Hardware',
  'Herp keeping',
  'Home improvement',
  'Homebrewing',
  'Homologation',
  'Houseplant care',
  'Hula hooping',
  'Humor',
  'Hydroponics',
  'Ice skating',
  'Jewelry making',
  'Jigsaw puzzles',
  'Journaling',
  'Juggling',
  'Karaoke',
  'Karate',
  'Kendama',
  'Knife making',
  'Knitting',
  'Knot tying',
  'Kombucha brewing',
  'Lace making',
  'Lapidary',
  'Leather crafting',
  'Lego building',
  'Livestreaming',
  'Lying',
  'Listening to music',
  'Listening to podcasts',
  'Lock picking',
  'Machining',
  'Mechanics',
  'Macrame',
  'Magic',
  'Makeup',
  'Mazes (indoor/outdoor)',
  'Meditation',
  'Metalworking',
  'Model building',
  'Model engineering',
  'Music',
  'Nail art',
  'Needlepoint',
  'Origami',
  'Painting',
  'Performance',
  'Planning',
  'Palmistry',
  'Pet',
  'Pet adoption & fostering',
  'Philately',
  'Photography',
  'Pilates',
  'Plastic art',
  'Playing musical instruments',
  'Poetry',
  'Poi',
  'Pole dancing',
  'Pottery',
  'Powerlifting',
  'Practical jokes',
  'Pressed flower craft',
  'Proverbs',
  'Puzzles',
  'Pyrography',
  'Quilling',
  'Quilting',
  'Quizzes',
  'Radio-controlled model playing',
  'Rail transport modeling',
  'Rapping',
  'Reading',
  'Refinishing',
  'Reiki',
  'Robot combat',
  'Rubiks Cube',
  'Saddlering',
  'Scrapbooking',
  'SCUBA Diving',
  'Sculpting',
  'Sewing',
  'Shoemaking',
  'Singing',
  'Sketching',
  'Skipping rope',
  'Slot car',
  'Soapmaking',
  'Social media',
  'Spreadsheets',
  'Stand-up comedy',
  'Stamp collecting',
  'Stripping',
  'Table tennis playing',
  'Tarot',
  'Taxidermy',
  'Thrifting',
  'Video editing',
  'Video game developing',
  'Video gaming',
  'Video making',
  'VR Gaming',
  'Watching movies',
  'Watching television',
  'Waxing',
  'Weaving',
  'Webtooning',
  'Weight training',
  'Welding',
  'Whittling',
  'Wikipedia editing',
  'Winemaking',
  'Wood carving',
  'Woodworking',
  'Word searches',
  'Worldbuilding',
  'Writing',
  'Yo-yoing',
  'Yoga',
  'Zumba',
  'Air sports',
  'Airsoft',
  'Amateur geology',
  'Amusement park visiting',
  'Archery',
  'Automobilism',
  'Astronomy',
  'Backpacking',
  'Badminton',
  'BASE jumping',
  'Baseball',
  'Basketball',
  'Beekeeping',
  'Birdwatching',
  'Blacksmithing',
  'BMX',
  'Board sports',
  'Bodybuilding',
  'Bonsai',
  'Butterfly watching',
  'Bus riding',
  'Camping',
  'Canoeing',
  'Canyoning',
  'Car riding',
  'Caving',
  'Composting',
  'Cycling',
  'Dowsing',
  'Driving',
  'Farming',
  'Fishing',
  'Flag football',
  'Flower growing',
  'Flying',
  'Flying disc',
  'Foraging',
  'Fossicking',
  'Freestyle football',
  'Gardening',
  'Geocaching',
  'Ghost hunting',
  'Gold prospecting',
  'Graffiti',
  'Handball',
  'Herbalism',
  'Herping',
  'High-power rocketry',
  'Hiking',
  'Hobby horsing',
  'Hobby tunneling',
  'Hooping',
  'Horseback riding',
  'Hunting',
  'Inline skating',
  'Jogging',
  'Jumping rope',
  'Karting',
  'Kayaking',
  'Kite flying',
  'Kitesurfing',
  'Lacrosse',
  'LARPing',
  'Letterboxing',
  'Lomography',
  'Longboarding',
  'Martial arts',
  'Metal detecting',
  'Modelism',
  'Motorcycling',
  'Meteorology',
  'Motor sports',
  'Mountain biking',
  'Mountaineering',
  'Museum visiting',
  'Mushroom hunting/mycology',
  'Netball',
  'Nordic skating',
  'Orienteering',
  'Paintball',
  'Parkour',
  'Photography',
  'Podcast hosting',
  'Polo',
  'Public transport riding',
  'Radio-controlled model playing',
  'Rafting',
  'Railway journeys',
  'Rappelling',
  'Road biking',
  'Rock climbing',
  'Roller skating',
  'Rugby',
  'Running',
  'Sailing',
  'Sand art',
  'Scouting',
  'Scuba diving',
  'Sculling or rowing',
  'Shooting',
  'Shopping',
  'Shuffleboard',
  'Skateboarding',
  'Skiing',
  'Skimboarding',
  'Skydiving',
  'Slacklining',
  'Snowboarding',
  'Snowmobiling',
  'Snowshoeing',
  'Soccer',
  'Stone skipping',
  'Sun bathing',
  'Surfing',
  'Survivalism',
  'Swimming',
  'Taekwondo',
  'Tai chi',
  'Tennis',
  'Thru-hiking',
  'Topiary',
  'Tourism',
  'Trade fair visiting',
  'Travel',
  'Urban exploration',
  'Vacation',
  'Vegetable farming',
  'Vehicle restoration',
  'Videography',
  'Walking',
  'Water sports',
  'Astronomy',
  'Biology',
  'Chemistry',
  'Electrochemistry',
  'Geography',
  'History',
  'Mathematics',
  'Medical science',
  'Microbiology',
  'Physics',
  'Psychology',
  'Railway studies',
  'Research',
  'Science and technology studies',
  'Social studies',
  'Sports science',
  'Action figure',
  'Antiquing',
  'Ant-keeping',
  'Art collecting',
  'Book collecting',
  'Button collecting',
  'Cartophily (card collecting)',
  'Coin collecting',
  'Comic book collecting',
  'Compact discs',
  'Deltiology (postcard collecting)',
  'Die-cast toy',
  'Digital hoarding',
  'Dolls',
  'Element collecting',
  'Ephemera collecting',
  'Films',
  'Fingerprint collecting',
  'Fusilately (phonecard collecting)',
  'Knife collecting',
  'Lotology (lottery ticket collecting)',
  'Movie memorabilia collecting',
  'Perfume',
  'Philately',
  'Phillumeny',
  'Pin (lapel)',
  'Radio-controlled model collecting',
  'Rail transport modelling',
  'Record collecting',
  'Rock tumbling',
  'Scutelliphily',
  'Shoes',
  'Slot car',
  'Sports memorabilia',
  'Stamp collecting',
  'Stuffed toy collecting',
  'Tea bag collecting',
  'Ticket collecting',
  'Toys',
  'Transit map collecting',
  'Video game collecting',
  'Vintage cars',
  'Vintage clothing',
  'Vinyl Records',
  'Antiquities',
  'Auto audiophilia',
  'Flower collecting and pressing',
  'Fossil hunting',
  'Insect collecting',
  'Magnet fishing',
  'Metal detecting',
  'Mineral collecting',
  'Rock balancing',
  'Sea glass collecting',
  'Seashell collecting',
  'Stone collecting',
  'Animal fancy',
  'Axe throwing',
  'Backgammon',
  'Badminton',
  'Baton twirling',
  'Beauty pageants',
  'Billiards',
  'Bowling',
  'Boxing',
  'Bridge',
  'Checkers (draughts)',
  'Cheerleading',
  'Chess',
  'Color guard',
  'Cribbage',
  'Curling',
  'Dancing',
  'Darts',
  'Debate',
  'Dominoes',
  'Eating',
  'Esports',
  'Fencing',
  'Go',
  'Gymnastics',
  'Ice hockey',
  'Ice skating',
  'Judo',
  'Jujitsu',
  'Kabaddi',
  'Knowledge/word games',
  'Laser tag',
  'Longboarding',
  'Magic',
  'Mahjong',
  'Marbles',
  'Martial arts',
  'Model racing',
  'Model United Nations',
  'Poker',
  'Pole dancing',
  'Pool',
  'Radio-controlled model playing',
  'Role-playing games',
  'Shogi',
  'Slot car racing',
  'Speedcubing',
  'Sport stacking',
  'Table football',
  'Table tennis',
  'Volleyball',
  'VR Gaming',
  'Weightlifting',
  'Wrestling',
  'Airsoft',
  'Archery',
  'Association football',
  'Australian rules football',
  'Auto racing',
  'Baseball',
  'Beach volleyball',
  'Breakdancing',
  'Climbing',
  'Cornhole',
  'Cricket',
  'Croquet',
  'Cycling',
  'Disc golf',
  'Dog sport',
  'Equestrianism',
  'Exhibition drill',
  'Field hockey',
  'Figure skating',
  'Fishing',
  'Fitness',
  'Footbag',
  'Frisbee',
  'Golfing',
  'Handball',
  'Horseback riding',
  'Horsemanship',
  'Horseshoes',
  'Iceboat racing',
  'Jukskei',
  'Kart racing',
  'Knife throwing',
  'Lacrosse',
  'Longboarding',
  'Long-distance running',
  'Marching band',
  'Model aircraft',
  'Orienteering',
  'Pickleball',
  'Powerboat racing',
  'Quidditch',
  'Race walking',
  'Racquetball',
  'Radio-controlled car racing',
  'Radio-controlled model playing',
  'Roller derby',
  'Rugby league football',
  'Sculling or rowing',
  'Shooting sport',
  'Skateboarding',
  'Skiing',
  'Sled dog racing',
  'Softball',
  'Speed skating',
  'Squash',
  'Surfing',
  'Swimming',
  'Table tennis',
  'Tennis',
  'Tennis polo',
  'Tether car',
  'Tour skating',
  'Tourism',
  'Trapshooting',
  'Triathlon',
  'Ultimate frisbee',
  'Volleyball',
  'Water polo',
  '',
  'Audiophile',
  'Fishkeeping',
  'Learning',
  'Meditation',
  'Microscopy',
  'Reading',
  'Research',
  'Shortwave listening',
  'Aircraft spotting',
  'Amateur astronomy',
  'Benchmarking',
  'Birdwatching',
  'Bus spotting',
  'Geocaching',
  'Gongoozling',
  'Herping',
  'Hiking/backpacking',
  'Meteorology',
  'Photography',
  'Satellite watching',
  'Trainspotting',
  'Whale watching',
];
