import LocalizedStrings from "react-native-localization";

const StringsOfLanguages = new LocalizedStrings({
  en: {
    loading: "loading",
    Cancel: "Cancel",
    Select: "select",
    sorryNo: "Sorry No",
    found: "found",
    User: "User",
    addFoto: "Add foto",

    imageLibrary: "Image Library",
    camera: "Camera",
    employee: "Employee",
    stockEdit: "Stock Edit",
    return: "Return",
    delivery: "Delivery",
    selectEmployee: "Select Employee",
    changePassword: "Change Password",
    resetPassword: "Reset Password",
    logout: "Logout",
    View: "View",
    Orders: "Orders",
    meterNumber: "Meter number",
    reading: "Reading",
    Document: "Document",
    Add: "Add",
    Order: "Order",
    OrderId: "Order-ID",
    Change: "Change",
    sendRestPasswordLink: "Send Password Reset Link",
    Appointment: "Appointment",
    password: "Password",
    taskType: "Task Type",
    task: "Task",
    pleaseEnter: "Please Enter",
    Status: "Status",
    taskText: "Task Text",
    Location: "Location",
    Vehicles: "Vehicles",
    Colleagues: "Colleagues",
    Details: "Details",
    documents: "Documents",
    timeRecord: "Time Record",
    productMask: "Product Mask",
    customOrder: "Custom Order",
    orderCategory: "Order Category",
    startDate: "Start Date",
    endDate: "End Date",
    Description: "Description",
    Customer: "Customer",
    contactPerson: "Contact Person",
    contactPhoneNumber: "Contact Phone Number",
    projectManager: "Project Manager",
    projectManagerPhoneNumber: "Project Manager Phone Number",
    Save: "Save",
    Start: "Start",
    Pause: "Pause",
    Resume: "Resume",
    allOrders: "All Orders",
    addNote: "Add Note",
    stop: "Stop",
    previousTask: "Previous Tasks",
    tasks: "Tasks",
    meterReading: "Meter Reading",
    recordMeterReading: "Record Meter Reading",
    selectOrder: "Select Orders",
    please: "Please",
    oldPassword: "Old Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Passoword",
    dates: "Dates",
    typeToFilterProducts: "Type to filter products",
    category: "Category",
    basicInformation: "Basic Information",
    productMovement: "Product Movement",
    recordTime: "Record Time",
    stockQty: "Stock Qty",
    action: "Action",
    quantity: "Quantity",
    productName: "Product Name",
    date: "Date",
    product: "Product",
    fileName: "File Name",
    changeLanguage: "Change Language",
    forgotPassword: "Forgot Password",
    signDocuments: "Sign Document",
    sign: "sign",
    performedWork: "Performed Work",
    recipient: "Recipient",
    customerName: "Customer Name",
    customerAddress: "Customer Address",
    customerCity: "Customer City",
    signPreview: "Signature Preview",
    signBoard: "Signature Board",
    saveContinue: "Save & Continue",
    sendEmail: "Send Email",
    signingPerson: "Signing Person",
    recordings: "Recordings",
    month: "Month",
    workTime: "Work Time",
    total: "Total",
    end: "End",
    totalHours: "Total Hours",
    targetHours: "Target Hours",
    difference: "difference",
    selectMonth: "Select Month",

    selectYear: "Select Year",
    year: "Year",
    delivered: "Delivered",
    returned: "Returned",
    signing: "Signing",
    selectFile: "Select File",
    addDocument: "Add Document",
    totalWorkTime: "Total Work Time ",
    endTime: "End time",
    pauseTime: "Pause Time",
    startTime: "Start Time",
    minutes: "mins",
    viewMonthlyTable: "View Monthly Table",
    editRecording: "Edit Recordings",
    dashboard: "Dashboard",
    selectCustomer: "Select Customer",
    selectLocation:"Select Location",
    clearRestart:"Clear & Restart"
  },
  de: {
    clearRestart:"Löschen und neu starten",
    selectLocation:"Ort auswählen",
    selectCustomer: "Kunden auswählen",
    dashboard: "Armaturenbrett",
    editRecording: "Aufnahmen bearbeiten",
    viewMonthlyTable: "Monatstabelle anzeigen",
    minutes: "Protokoll",
    startTime: "Startzeit",

    pauseTime: "Pausenzeit",
    endTime: "Endzeit",
    totalWorkTime: "Gesamtarbeitszeit",
    addDocument: "Dokument hinzufügen",
    selectFile: "Datei aussuchen",
    signing: "Unterzeichnung",
    returned: "ist zurückgekommen",
    delivered: "geliefert",
    year: "Jahr",
    selectYear: "Jahr auswählen",
    selectMonth: "Wähle einen Monat",
    difference: "Unterschied",
    targetHours: "Zielstunden",
    totalHours: "Gesamtstunden",
    records: "Aufzeichnungen",
    contactPhoneNumber: "Kontakt Telefonnummer",
    end: "Ende",
    total: "gesamt",
    workTime: "Arbeitszeit",
    month: "Monat",
    recordings: "Aufnahmen",
    signingPerson: "Unterzeichnende Person",
    sendEmail: "E-Mail senden",
    saveContinue: "Speichern und fortfahren",
    signBoard: "Unterschriftentafel",
    signPreview: "Unterschriftenvorschau",
    customerCity: "Kundenstadt",
    recipient: "Empfänger",
    customerName: "Kundenname",
    customerAddress: "Kundenadresse",
    performedWork: "Ausgeführte Arbeit",
    sign: "Schild",
    signDocuments: "Dokument unterschreiben",
    changeLanguage: "Sprache ändern",
    product: "Material",
    fileName: "Dateiname",
    date: "Datum",
    productName: "Name Material",
    quantity: "Menge",
    action: "Aktion",
    stockQty: "Bestand Menge",
    task: "Aufgabe",
    return: "Abbau",
    delivery: "Lieferung",
    loading: "Wird geladen",
    Cancel: "abbrechen",
    Select: "auswählen",
    please: "Bitte",
    password: "Passwort",
    sorryNo: "Entschuldige Nein",
    found: "Gefunden",
    User: "Benutzer",
    addFoto: "Foto hinzufügen",
    imageLibrary: "Bildarchiv",
    camera: "Kamera",
    employee: "Mitarbeiter",
    selectEmployee: "Mitarbeiter auswählen",
    changePassword: "Passwort ändern",
    resetPassword: "Passwort zurücksetzen",
    allOrders: "Aufträge",
    logout: "Logout",
    View: "Anzeigen",
    Orders: "Aufträge",
    meterNumber: "Zählernummer",
    reading: "Zählerstand",
    Document: "Dokument",
    documents: "Unterlagen",
    Add: "hinzufügen",
    Change: "Ändern",
    Order: "Projekt",
    OrderId: "Bestellnummer",
    sendRestPasswordLink: "Passwort Link senden",
    Appointment: "Termin",
    taskType: "Aufgabentyp",
    Status: "Status",
    taskText: "Aufgabe Text",
    Location: "Ort",
    Vehicles: "Fuhrpark",
    Colleagues: "Kollegen",
    Details: "Einzelheiten",
    timeRecord: "Zeiterfassung",
    productMask: "Lieferschein erfassen",
    customOrder: "Individuelles Projekt",
    orderCategory: "Projektkategorie",
    startDate: "Aufbau Datum",
    endDate: "Projektende",
    Description: "Beschreibung",
    Customer: "Kunde",
    contactPerson: "Ansprechpartner",
    projectManager: "Projektleiter",
    projectManagerPhoneNumber: "Projektleiter Telefonnummer",
    Save: "Speichern",
    Start: "Start",
    Pause: "Pause",
    Resume: "Fortsetzen",
    addNote: "Notiz hinzufügen",
    stop: "Halt",
    basicInformation: "Grundinformation",
    forgotPassword: "Passwort vergessen",
    previousTask: "Vorherige Aufgaben",
    tasks: "Aufgaben",
    meterReading: "Zählerstand",
    recordMeterReading: "Zählerstand aufzeichnen",
    selectOrder: "Projekte auswählen",
    oldPassword: "Altes Passwort",
    newPassword: "Neues Passwort",
    confirmPassword: "Passwort bestätigen",
    dates: "Daten",
    typeToFilterProducts: "Tippen um Material zu filtern...",
    category: "Kategorie",
    pleaseEnter: "Bitte eingeben",
    productMovement: "Materialbewegungen",
    recordTime: "Arbeitszeit aufzeichnen",
    stockEdit: "Bestand bearbeiten",
  },
});

export default StringsOfLanguages;
